### ISSUE TITLE
Release Read the Docs

### ISSUE THREAD

**Issue by itdependsnetworks** [LinuxRocks2000/netutils#1]
Hi, it seems you have moved the name to serverutils, do you mind releasing the read the docs page? https://readthedocs.org/projects/netutils/

**Comment by itdependsnetworks** [comment]
For more context as to my interest, https://github.com/networktocode/netutils

**Comment by LinuxRocks2000** [comment]
Done. Hope Netutils turns out to actually work, unlike serverutils!

**Comment by itdependsnetworks** [comment]
You sir Rock!!
